"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { AuthProvider } from "@/Components/Providers/AuthProvider";
import { Stack, ThemeProvider } from "@mui/material";
import { theme } from "./theme";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import { DataProvider } from "@/Components/Providers/DataProvider";
import { Header } from "@/Components/Header/Header";
import { Navbar } from "@/Components/Header/Navbar";
import { Footer } from "@/Components/Header/Footer";
import { useState } from "react";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [test, setTest] = useState();
  const pathname = usePathname();

  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <AuthProvider>
              <DataProvider>
                {pathname.search("Merchant") < 0 && (
                  <Stack>
                    <Header />
                    <Navbar />
                  </Stack>
                )}

                {children}
                {pathname.search("Merchant") < 0 && <Footer />}
              </DataProvider>
            </AuthProvider>
            <ToastContainer />
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
